In [133]:
import numpy as np 
import tensorflow as tf
from tensorflow import keras
import random

sample_data = np.array([[0.0, 0.0, 0.0, 0.0]])
sample_targets = np.array([0])

for i in range(0,5000):
    random_number = random.randrange(1, 10000) -5000 # generate a number between -5000 and 5000
    sample_data = np.append(sample_data,[[random_number,random_number,random_number,random_number]],axis=0)
    sample_targets = np.append(sample_targets,[4*random_number],axis=0)

train_data = sample_data[:int(len(sample_data) * 0.8)]
train_targets = sample_targets[:int(len(sample_targets) * 0.8)]
test_data = sample_data[int(len(sample_data) * 0.8):]
test_targets = sample_targets[int(len(sample_targets) * 0.8):]

print("Train set input: \n", train_data)
print("Train set label: \n", train_targets)

Train set input: 
 [[    0.     0.     0.     0.]
 [-3442. -3442. -3442. -3442.]
 [ 3071.  3071.  3071.  3071.]
 ...
 [ -762.  -762.  -762.  -762.]
 [-1832. -1832. -1832. -1832.]
 [  822.   822.   822.   822.]]
Train set label: 
 [     0 -13768  12284 ...  -3048  -7328   3288]


In [134]:
model = keras.Sequential([
    keras.layers.Input(shape=(4,)),
    keras.layers.Dense(20, activation=tf.nn.relu),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', 
              loss='mse',
              metrics=['mae'])

model.fit(train_data, train_targets, epochs=10, batch_size=1)

Epoch 1/10
4000/4000 [==============================] - 6s 2ms/step - loss: 5944356.5000 - mae: 681.6017
Epoch 2/10
4000/4000 [==============================] - 6s 2ms/step - loss: 0.2349 - mae: 0.4039
Epoch 3/10
4000/4000 [==============================] - 6s 2ms/step - loss: 1553.3771 - mae: 7.8098
Epoch 4/10
4000/4000 [==============================] - 6s 2ms/step - loss: 5711.9458 - mae: 12.7150
Epoch 5/10
4000/4000 [==============================] - 6s 2ms/step - loss: 1585.9246 - mae: 8.9726
Epoch 6/10
4000/4000 [==============================] - 6s 2ms/step - loss: 1777.8549 - mae: 10.8244
Epoch 7/10
4000/4000 [==============================] - 6s 1ms/step - loss: 2571.5803 - mae: 10.1760
Epoch 8/10
4000/4000 [==============================] - 6s 1ms/step - loss: 1010.4409 - mae: 8.9737
Epoch 9/10
4000/4000 [==============================] - 6s 2ms/step - loss: 1592.3505 - mae: 10.7729
Epoch 10/10
4000/4000 [==============================] - 6s 2ms/step - loss: 994.4719 - mae: 7

In [135]:
test_loss, test_mae = model.evaluate(test_data, test_targets, verbose = 1)
print('Test lost:', test_loss)
print('Test mae:', test_mae)

a= np.array([[1,2,3,4],[2000,3000,4000,5000],[4,5,6,7],[-20,-30,-40,-50]])
np.set_printoptions(suppress=True)
print('Test input:\n', a)
print('Test output:\n',model.predict(a))

32/32 [==============================] - 0s 2ms/step - loss: 0.9372 - mae: 0.6691
Test lost: 0.9371962547302246
Test mae: 0.6691457033157349
Test input:
 [[   1    2    3    4]
 [2000 3000 4000 5000]
 [   4    5    6    7]
 [ -20  -30  -40  -50]]
Test output:
 [[   10.900178]
 [14374.755   ]
 [   22.883434]
 [ -137.96759 ]]
