In [103]:
import numpy as np 
import tensorflow as tf
from tensorflow import keras

np.set_printoptions(suppress=True)

max_input_length = 20

sample_data = np.zeros((1, 20))
sample_targets= np.zeros((1, 1))

for i in range(0,5000):
    n = np.random.randint(20)
    random_number = random.randrange(1, 10000) -5000 # generate a number between -5000 and 5000
    new_row =  np.append(np.full([n],random_number), np.zeros((1,max_input_length-n)))
    sample_data = np.append(sample_data,[new_row],axis=0)
    sample_targets= np.append(sample_targets,[random_number*n])

train_data = sample_data[:int(len(sample_data) * 0.8)]
train_targets = sample_targets[:int(len(sample_targets) * 0.8)]
test_data = sample_data[int(len(sample_data) * 0.8):]
test_targets = sample_targets[int(len(sample_targets) * 0.8):]

print("Train set inputs: \n", train_data)
print("Train set labels: \n", train_targets)

Train set inputs: 
 [[    0.     0.     0. ...     0.     0.     0.]
 [-1108. -1108. -1108. ...     0.     0.     0.]
 [ -830.  -830.  -830. ...     0.     0.     0.]
 ...
 [ -108.  -108.  -108. ...  -108.     0.     0.]
 [-4002. -4002. -4002. ...     0.     0.     0.]
 [-3624.     0.     0. ...     0.     0.     0.]]
Train set labels: 
 [     0.  -4432.  -8300. ...  -1944. -60030.  -3624.]


In [104]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(max_input_length,)),
    keras.layers.Dense(20, activation=tf.nn.relu),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', 
              loss='mse',
              metrics=['mae'])

model.fit(train_data, train_targets, epochs=10, batch_size=1)

Epoch 1/10
4000/4000 [==============================] - 7s 2ms/step - loss: 71357352.0000 - mae: 2886.9290
Epoch 2/10
4000/4000 [==============================] - 6s 2ms/step - loss: 164995.0312 - mae: 263.0319
Epoch 3/10
4000/4000 [==============================] - 6s 2ms/step - loss: 58956.7969 - mae: 117.5431
Epoch 4/10
4000/4000 [==============================] - 6s 1ms/step - loss: 60016.7891 - mae: 117.4528
Epoch 5/10
4000/4000 [==============================] - 6s 1ms/step - loss: 82526.7656 - mae: 103.6758
Epoch 6/10
4000/4000 [==============================] - 6s 2ms/step - loss: 59719.7344 - mae: 103.4850
Epoch 7/10
4000/4000 [==============================] - 6s 2ms/step - loss: 43999.6133 - mae: 94.0392
Epoch 8/10
4000/4000 [==============================] - 6s 1ms/step - loss: 48012.9258 - mae: 103.6960
Epoch 9/10
4000/4000 [==============================] - 6s 1ms/step - loss: 66400.4766 - mae: 100.3150
Epoch 10/10
4000/4000 [==============================] - 6s 1ms/step 

In [105]:
test_loss, test_mae = model.evaluate(test_data, test_targets, verbose = 1)
print('Test lost:', test_loss)
print('Test mae:', test_mae)

a= np.array([
     np.append([0.1,0.2], np.zeros(18),axis=0),
     np.append([2000,3000,4000,5000], np.zeros(16),axis=0),     
     np.append([1,2,3,4,5,6,7,8,9,10], np.zeros(10),axis=0), 
     np.append([-1,-2,-3], np.zeros(17),axis=0),   
     ])
print(model.predict(a))


32/32 [==============================] - 0s 1ms/step - loss: 1152.1237 - mae: 21.0614
Test lost: 1152.1236572265625
Test mae: 21.061399459838867
[[    0.3796237]
 [13948.6045   ]
 [   55.153774 ]
 [   -6.475255 ]]
